export const actionTypes = {
  SET_SORT_BY: "SET_SORT_BY",
  SET_CATEGORY: "SET_CATEGORY",

  SET_PIZZAS: "SET_PIZZAS",
  SET_LOADED_FLAG: "SET_LOADED_FLAG",

  ADD_PIZZA_ITEM_TO_CART: "ADD_PIZZA_ITEM_TO_CART",
  CLEAR_CART: "CLEAR_CART",

  DELETE_CART_PIZZA: "DELETE_CART_PIZZA",
  DECREASE_COUNT_PIZZA_ITEMS: "DECREASE_COUNT_PIZZA_ITEMS",
  INCREASE_COUNT_PIZZA_ITEMS: "INCREASE_COUNT_PIZZA_ITEMS",
};
